---
title: "R Notebook"
output: html_notebook
---

Basic Data manicupaltion (Wide to Long)
```{r include=FALSE}
x<-c('tidyverse','reshape2','splines','ggthemes','tlnise','gridExtra','data.table','zoo','forcats','broom')
lapply(x, require, character.only=T)
#setwd('K:\\Research\\PMSource_Hosp\\Code\\R\\NoteBook')
options(dplyr.width = Inf)

load("C:\\Users\\kebisu\\Documents\\Research\\PMSource_Hosp\\Data\\OriginalData_20171214.RData") #Original_df

Original_df2 = Original_df %>% 
     select(-cardio_disease_age19to49, -cardio_disease_age50to64, -resp_disease_age19to49, -resp_disease_age50to64) %>% 
     select(Name, Zone, date, cardio_disease_white0to18:resp_disease_hispanic75up) %>% 
     gather(variable, measurement, cardio_disease_white0to18:resp_disease_hispanic75up, factor_key=TRUE) %>% 
     mutate(Race = str_extract(variable, pattern = "(white)|(hispanic)|(asian)|(black)"), 
         Age = str_extract(variable, pattern = "(0to18)|(19to49)|(50to64)|(65to74)|(75up)"),
         disease = str_extract(variable, pattern = "(cardio)|(resp)")) %>% 
     mutate(disease = replace(disease, disease == 'cardio', 'Cardio'), disease = replace(disease, disease == 'resp', 'Resp'), Age = replace(Age, Age == '0to18', '00to18'), Age = replace(Age, Age == '75up', '75to99')) %>% 
     mutate(Age3 = case_when(Age == '00to18' ~ '00to18', Age == '19to49' ~ '19to64', Age == '50to64' ~ '19to64', Age =='65to74' ~ '65to99', Age == '75to99' ~ '65to99')) %>% 
     select(Name, Zone, date, disease, Age3, Race, measurement) %>% 
     arrange(Name, Zone, date, disease, Age3, Race) %>% 
     rename(Age = Age3)
Original_df2$Name = as.character(Original_df2$Name)
Original_df2$Race = as.factor(Original_df2$Race )
Original_df2$Race = relevel(Original_df2$Race ,ref='white')
Original_df2$Age = as.factor(Original_df2$Age )
Original_df2$Age = relevel(Original_df2$Age ,ref='19to64')

```

Now Let's rearrange data to the way I want to analyze
```{r}
#This air dataset is coming from K:\Research\PMSource_LBW\Code\R\AirData.R
air_df = read.csv('K:\\Research\\PMSource_LBW\\Data\\AirData_20160520.csv', stringsAsFactors=F)
air_df$date = as.Date(air_df$date, format = "%m/%d/%Y")
 # Weather Data better cireate other file
load('K:\\Research\\PMSource_Hosp\\Data\\WeatherData.RData') #WeatherData
WeatherData = rename(WeatherData,date = DATE)
WeatherData$Name = as.character(WeatherData$Name)

# Exposure variables and related variables
Hol_List=c('2002-01-01','2002-05-27','2002-07-04','2002-09-02','2002-11-28','2002-12-25',
           '2003-01-01','2003-05-26','2003-07-04','2003-09-01','2003-11-27','2003-12-25',
           '2004-01-01','2004-05-31','2004-07-04','2004-09-06','2004-11-25','2004-12-25',
           '2005-01-01','2005-05-30','2005-07-04','2005-09-05','2005-11-24','2005-12-25',
           '2006-01-01','2006-05-29','2006-07-04','2006-09-04','2006-11-23','2006-12-25',
           '2007-01-01','2007-05-28','2007-07-04','2007-09-03','2007-11-22','2007-12-25',
           '2008-01-01','2008-05-26','2008-07-04','2008-09-01','2008-11-27','2008-12-25',
           '2009-01-01','2009-05-25','2009-07-04','2009-09-07','2009-11-26','2009-12-25')
Hol_List=as.Date(Hol_List,"%Y-%m-%d")

# Merge Air, Weather, and calendar info data
AirWeather = Original_df2 %>% 
     distinct(Name, date) %>% 
     left_join(air_df, by =c('Name','date')) %>% 
     left_join(WeatherData, by =c('Name', 'date')) %>% 
     select(-Site, -loca, -SITE, -stn_id) %>% 
     mutate(DOW=weekdays(date),     
            Weekend=case_when(DOW=='Saturday'~1,DOW=='Sunday'~1,DOW=='Monday'~0,DOW=='Tuesday'~0,
                              DOW=='Wednesday'~0,DOW=='Thursday'~0,DOW=='Friday'~0),
            day=as.numeric(date-as.Date('2001-12-31')),
            Holiday=ifelse(date %in% Hol_List,1,0),
            HolWend=ifelse(Weekend==1,1,ifelse(Holiday==1,1,0)))  %>% 
     arrange(Name, date)     

AirWeather2 = data.table(AirWeather)
setkey(AirWeather2,Name, date)
AirWeather2[,index_temp:=rollapply(HolWend,2,sum,align=c('right'),fill=NA,na.rm=TRUE,partial=TRUE),by=Name]
AirWeather2 = data.frame(AirWeather2)
AirWeather2 = mutate(AirWeather2, AfterHolWend = ifelse(HolWend==0 & index_temp==1, 1, 0),
            DayIndex = ifelse(HolWend==1,'HolWend',ifelse(AfterHolWend==1,'AfterHolWend','Weekday'))) %>% 
     select(-index_temp)
AirWeather2$DayIndex = as.factor(AirWeather2$DayIndex)
AirWeather2$DayIndex = relevel(AirWeather2$DayIndex,ref='Weekday')

warm = c('05','06','07','08','09','10')
AirWeather2 = mutate(AirWeather2, Warm = ifelse(substr(date,6,7) %in% warm, 1, 0), Cool = ifelse( Warm == 1, 0, 1 ), YEAR = as.factor(substr(date, 1, 4)), Year_Con = as.numeric(substr(date, 1, 4))) 

#Create Data for Analysis
DF = filter(Original_df2, Zone!='C') %>% 
    filter(Age == '00to18') %>% 
#     filter(substr(date, 1,4) < 2008) %>% 
     group_by(Name,date, disease, Race) %>%  #Add/Remove varible here in which level I want to analyze
#     filter(Race == 'white') %>% 
     summarise(Case = sum(measurement)) %>% 
     data.frame() %>%     
     left_join(AirWeather2, by = c('Name', 'date')) 
```
Now Let's analyze data using new data frame

```{r}
OutComeList = c('Cardio','Resp')
ExpList = c("totpm25","secsulf","secnit","vehic","biomass","soil","fsalt","asalt","Al","NH4.","Sb","As","Ba","Br","Cd","Ca","Ce","Cs","Cl","Cr","Co","Cu","EC","In","Fe","Pb","Mg","Mn","Ni","OC","P","K","Rb","Se","Si","Ag","Na","K.","NA.","Sr","SO42.","S","Sn","Ti","NO3.","V","Zn","Zr")
LagNum = c(0:2)
Place = c('BAK','ELC','FRE','LAX','RUB','SAC','SJO','SVY')
alllist = expand.grid(OutComeList, ExpList, LagNum, Place) #Create all possible combinations 
names(alllist)=c('Outcome','Exposure','Lag', 'Place') #Label columns
alllist$Outcome=as.character(alllist$Outcome)
alllist$Exposure=as.character(alllist$Exposure)
alllist$Place = as.character(alllist$Place)
alllist$denomi = c('Pop')


df.temp=3
df.rh=3
df.day=4*8 #4/year*8 years

PoisModel<-function(datasetname){
#     covariates=c('exposure_cool','exposure_warm','DayIndex','Race','ns(meanapptemp,df.temp)','ns(day,df.day)',  'Warm') 
     covariates=c('exposure','exposure_warm','DayIndex','Race','ns(meanapptemp,df.temp)','ns(day,df.day)')
#      covariates=c('exposure','exposure_cool','DayIndex','ns(meanapptemp,df.temp)','ns(day,df.day)')
#     covariates=c('exposure_cool','exposure_warm','DayIndex','Race','ns(meanapptemp,df.temp)','ns(day,df.day)','YEAR')      
#     covariates=c('exposure_cool','exposure_warm','DayIndex','Race','ns(meanapptemp,df.temp)','YEAR','Warm') 
#     covariates=c('exposure_cool','exposure_warm','DayIndex')     
     model=as.formula(paste("Case~",paste(covariates,collapse="+")))
     fit=glm(model,
             data=datasetname,
             family=quasipoisson,
             na.action = na.exclude,
             control=glm.control(maxit = 1000,epsilon = 1e-8))
     summary(fit)
}

pol_list = c("totpm25","secsulf","secnit","vehic","biomass","soil")
alllist = filter (alllist, Exposure %in% pol_list)

Result.1st = list()
ptm=proc.time()
for (iii in 1:dim(alllist)[1]){
     tryCatch({ 
     tempname=alllist[iii,2]
     DF$target_val = DF[,c(tempname)]
     DF_temp = DF %>% 
          filter(Name == alllist[iii, 4], disease == alllist[iii,1]) %>% 
          arrange(date) %>%
          group_by(Race) %>% 
          mutate(exposure = lag(target_val, n = alllist[iii,3], default = NA), exposure_warm = exposure*Warm, exposure_cool = exposure*Cool) %>% 
          ungroup() %>% 
          filter(!is.na(exposure_warm) & !is.na(meantemp)) 
     out1 = PoisModel(DF_temp)
     temp_matrix = out1$cov.unscaled[c(2:3),c(2:3)] * out1$dispersion 
     out = cbind(out1$coefficients[c(2:3),], data.frame(temp_matrix))
     out = out %>% 
          mutate(variable = rownames(.), Outcome = alllist[iii,1], Pollutant = alllist[iii,2], Lag = alllist[iii,3], Place = alllist[iii,4])
     Result.1st[[iii]] <- out    
     rm(DF_temp, out1, out)
     }, error=function(e){})           
}
proc.time() - ptm
Result.1stall = do.call(rbind, Result.1st)
names(Result.1stall)[1] = 'estimate'
names(Result.1stall)[4] = 'p.value'

filter(Result.1stall,  p.value<0.05, estimate>0) %>% arrange(estimate)
filter(Result.1stall,  p.value<0.05, estimate<0) %>% arrange(estimate)
```
Second Stage Analysis
```{r include=FALSE}
ExpList2 = c(ExpList,'Cool')
Air_season = DF %>% 
     select_( .dots = ExpList2) %>% 
     group_by(Cool) %>% 
     summarize_all(funs(IQR),na.rm=TRUE) %>% 
     t() %>%
     data.frame() %>% 
     rename(Summer = 'X1', Winter = 'X2') %>% 
     mutate(Pollutant = rownames(.)) %>% 
     melt(id.vars=c('Pollutant')) %>% 
     mutate(Variable = case_when(variable == 'Summer'~ "exposure_warm", variable == 'Winter' ~ 'exposure_cool')) %>%
     filter(Pollutant != 'Cool') %>% 
     rename (IQR = value) %>% 
     select(Variable, Pollutant, IQR)

# If want to use annual IQR, use this code
Air_year = select_(DF, .dots = ExpList) %>% 
     summarize_all(funs(IQR),na.rm=TRUE) %>% 
     t() %>%
     data.frame() %>% 
     rename(IQR=".") 
Air_year$Pollutant=rownames(Air_year)
rownames(Air_year)=c(1:dim(Air_year)[1])
Air_year$Variable = 'exposure'


Air = rbind(Air_season, Air_year)

alllist2=distinct(Result.1stall,Outcome,Pollutant,Lag,keep_all=TRUE)

tlnise.result = list()
for (mm in 1:dim(alllist2)[1]){
     temp2nd=filter(Result.1stall, Outcome == alllist2[mm,1], Pollutant == alllist2[mm,2], Lag == alllist2[mm,3])
     set.seed(21)
     prior = 0
     seed <- round(10000*runif(1))
     beta = select(temp2nd, Place, estimate, variable) %>% 
          dcast(Place~ variable, value.var = 'estimate') %>% 
          select(-Place)
     covarint <- array(NA,c(2,2,dim(beta)[1]))
          for (nnn in 1:dim(beta)[1]){
          tt = as.matrix(temp2nd[c((nnn*2-1):(nnn*2)),c(5:6)])
          covarint[,,nnn]= tt
          rm(tt)
     }
     tlnise.out = tlnise(beta,covarint, prior=prior, maxiter=5000, seed=seed) 
     tlnise.out2 = tlnise.out$gamma %>% 
          data.frame() %>% 
          mutate(Outcome = alllist2[mm,1], Pollutant = alllist2[mm,2], Lag = alllist2[mm,3], N= dim(beta)[1],Variable = names(beta)) %>% 
          select(Outcome, Pollutant, Lag, N, Variable, est, se, est.se)
     tlnise.result[[mm]] = tlnise.out2
     rm(temp2nd, beta, covarint, tlnise.out, tlnise.out2)
}
tlnise.result2= do.call(rbind, tlnise.result)

```

```{r}
tlnise.result3 = tlnise.result2 %>% 
     rename(PE = est, SE = se) %>% 
     mutate(Z = PE/SE, P = 1 - 2*abs(0.5-(1-pnorm(Z)))) %>% 
     inner_join(Air, by = c('Variable','Pollutant')) %>% 
     mutate(Effect = exp(PE*IQR), LCI = exp((PE-1.96*SE)*IQR), UCI = exp((PE+1.96*SE)*IQR))

filter(tlnise.result3,UCI<1) %>% arrange(Effect) %>% select(Outcome,Pollutant, Variable, Lag, N, IQR, Effect, LCI, UCI)
filter(tlnise.result3,LCI>1) %>% arrange(Effect) %>% select(Outcome,Pollutant, Variable, Lag, N, IQR, Effect, LCI, UCI)

tlnise.result3 %>% filter(P<0.10)
```

Make a plot
```{r}
tlnise.result4 = mutate(tlnise.result3, Name=case_when(Pollutant == 'asalt'~ "Aged Sea Salt",
                                                 Pollutant == 'soil'~"Soil",
                                                  Pollutant == 'biomass' ~ "Biomass",
                                                  Pollutant == 'secnit' ~ "Secondary Nitrate",
                                                  Pollutant == 'secsulf' ~ "Secondary Sulfate",
                                                  Pollutant == 'fsalt' ~ "Fresh Sea Salt",
                                                  Pollutant == 'vehic' ~ "Vehicle Emission",
                                                  Pollutant == 'totpm25' ~ 'PM2.5'),
                                        LineCol = case_when(PE < 0 & P < 0.05 ~ 'blue',
                                                            PE < 0 & P < 0.10 ~ 'green',
                                                            PE > 0 & P < 0.05 ~ 'red',
                                                            PE > 0 & P < 0.10 ~ 'orange',
                                                            TRUE ~ 'black'),
                                        Sh_type = ifelse(P <0.05, 16, 1 ))

tlnise.result4 = filter(tlnise.result4, Pollutant!='fsalt'& Pollutant!='asalt')
tlnise.result4$Name[tlnise.result4$Name=='PM2.5'] = '"PM[2.5]"'
tlnise.result4$Name = factor(tlnise.result4$Name)
tlnise.result4$Name = relevel(tlnise.result4$Name,'"PM[2.5]"')
tlnise.result4$Pollutant = factor(tlnise.result4$Pollutant)
tlnise.result4$Pollutant = relevel(tlnise.result4$Pollutant,'totpm25')
tlnise.result4$Lag = as.factor(tlnise.result4$Lag)

#save(tlnise.result4, file = 'K:\\Research\\PMSource_Hosp\\Data\\Result\\Result_SeasonStrat_RaceAdjust.RData')

OutcomeList = select(tlnise.result4, Outcome) %>%
          distinct(Outcome, Pollutant)

Cardio = filter(tlnise.result4, Outcome == 'Cardio') %>% 
     ggplot(aes(x=Lag,y=Effect,color=Variable)) +
     	geom_errorbar(aes(ymin=LCI,ymax=UCI),size=1,width=0.35,position = position_dodge(width = 0.50))+
     	geom_point(aes(), cex=3.25,position = position_dodge(width = 0.50))+
          facet_grid(.~Pollutant)+
     	geom_hline(yintercept=1,color='Black')+ 
          ylab("OR per IQR increase")+
          xlab("")+
          ggtitle('Cardiovascular related Hospital Admission')+
          theme_bw()+
          scale_colour_manual(values=c("grey1", "firebrick2"), name = 'Season', breaks=c('exposure_warm', 'exposure'),labels=c('Warm','YearBase'))+
          theme(plot.title = element_text(hjust = 0.5), 
                axis.text.x = element_text(vjust =0.5, angle = 0), panel.grid.major = element_blank(),
                panel.grid.minor = element_blank())

Resp = filter(tlnise.result4, Outcome == 'Resp') %>% 
     ggplot(aes(x=Lag,y=Effect,color=Variable)) +
     	geom_errorbar(aes(ymin=LCI,ymax=UCI),size=1,width=0.35,position = position_dodge(width = 0.50))+
     	geom_point(aes(),cex=3.25,position = position_dodge(width = 0.50))+
          facet_grid(.~Pollutant)+
     	geom_hline(yintercept=1,color='Black')+ 
          ylab("OR per IQR increase")+
          xlab("")+
          ggtitle('Respiratory related Hospital Admission')+
          theme_bw()+
         scale_colour_manual(values=c("grey1", "firebrick2"), name = 'Season', breaks=c('exposure_warm', 'exposure'),labels=c('Warm','YearBase'))+
          theme(plot.title = element_text(hjust = 0.5), 
                axis.text.x = element_text(vjust =0.5, angle = 0), panel.grid.major = element_blank(),
                panel.grid.minor = element_blank())

grid.arrange(Cardio, Resp, ncol=1)

```